export interface TokenListItem {
  chainId: number;
  address: `0x${string}`;
  name: string;
  symbol: string;
  decimals: number;
  logoURI: string;
  tags?: string[];
}

export interface TokenListResponse {
  tokens: TokenListItem[];
}

// TODO: API response를 여기에 넣어주세요
export const TOKEN_LIST: TokenListResponse = {
  tokens: [
    {
      chainId: 998,
      address: '0x2673c0EcF19cE39A47F5f0aE72322496e96556EE',
      decimals: 6,
      name: 'USDT0',
      symbol: 'USDT0',
      tags: ['Top', 'Stablecoins'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/USDT0.png',
    },
    {
      chainId: 998,
      address: '0x68CD2D3503cB4A334522E557c5BA1a0d5Fe56bfC',
      decimals: 18,
      name: 'Wrapped HYPE',
      symbol: 'WHYPE',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/HYPE.png',
    },
    {
      chainId: 998,
      address: '0x4f9Ad8Fb8E1250fDcdd45d9ED23B6993E5177C54',
      decimals: 18,
      name: 'UETH',
      symbol: 'UETH',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/UETH.png',
    },
    {
      chainId: 999,
      address: '0x47bb061c0204af921f43dc73c7d7768d2672ddee',
      decimals: 6,
      name: 'BUDDY',
      symbol: 'BUDDY',
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/BUDDY.png',
    },
    {
      chainId: 999,
      address: '0x02c6a2fa58cc01a18b8d9e00ea48d65e4df26c70',
      decimals: 18,
      name: 'feUSD',
      symbol: 'feUSD',
      tags: ['Stablecoins'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/feUSD.png',
    },
    {
      chainId: 999,
      address: '0xfDD22Ce6D1F66bc0Ec89b20BF16CcB6670F55A5a',
      decimals: 6,
      name: 'thBILL',
      symbol: 'thBILL',
      tags: ['Stablecoins'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/thBILL.svg',
    },
    {
      chainId: 999,
      address: '0x5555555555555555555555555555555555555555',
      decimals: 18,
      name: 'Wrapped HYPE',
      symbol: 'WHYPE',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/HYPE.png',
    },
    {
      chainId: 999,
      address: '0x5748ae796ae46a4f1348a1693de4b50560485562',
      decimals: 18,
      name: 'LHYPE',
      symbol: 'LHYPE',
      tags: ['LST'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/LHYPE.png',
    },
    {
      chainId: 999,
      address: '0x1ecd15865d7f8019d546f76d095d9c93cc34edfa',
      decimals: 18,
      name: 'LIQD',
      symbol: 'LIQD',
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/LIQD.png',
    },
    {
      chainId: 999,
      address: '0x9b498c3c8a0b8cd8ba1d9851d40d186f1872b44e',
      decimals: 18,
      name: 'PURR',
      symbol: 'PURR',
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/PURR.png',
    },
    {
      chainId: 999,
      address: '0xffaa4a3d97fe9107cef8a3f48c069f577ff76cc1',
      decimals: 18,
      name: 'stHYPE',
      symbol: 'stHYPE',
      tags: ['LST'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/stHYPE.png',
    },
    {
      chainId: 999,
      address: '0x9fdbda0a5e284c32744d2f17ee5c74b284993463',
      decimals: 8,
      name: 'UBTC',
      symbol: 'UBTC',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/UBTC.png',
    },
    {
      chainId: 999,
      address: '0xbe6727b535545c67d5caa73dea54865b92cf7907',
      decimals: 18,
      name: 'UETH',
      symbol: 'UETH',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/UETH.png',
    },
    {
      chainId: 999,
      address: '0x3b4575e689ded21caad31d64c4df1f10f3b2cedf',
      decimals: 6,
      name: 'UFART',
      symbol: 'UFART',
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/UFART.png',
    },
    {
      chainId: 999,
      address: '0x27ec642013bcb3d80ca3706599d3cda04f6f4452',
      decimals: 6,
      name: 'UPUMP',
      symbol: 'UPUMP',
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/UPUMP.png',
    },
    {
      chainId: 999,
      address: '0xb50a96253abdf803d85efcdce07ad8becbc52bd5',
      decimals: 6,
      name: 'USDHL',
      symbol: 'USDHL',
      tags: ['Stablecoins'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/USDHL.png',
    },
    {
      chainId: 999,
      address: '0xb8ce59fc3717ada4c02eadf9682a9e934f625ebb',
      decimals: 6,
      name: 'USDT0',
      symbol: 'USDT0',
      tags: ['Stablecoins'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/USDT0.png',
    },
    {
      chainId: 999,
      address: '0x068f321fa8fb9f0d135f290ef6a3e2813e1c8a29',
      decimals: 9,
      name: 'USOL',
      symbol: 'USOL',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/USOL.png',
    },
    {
      chainId: 999,
      address: '0x9fd7466f987fd4c45a5bbde22ed8aba5bc8d72d1',
      decimals: 6,
      name: 'hwHLP',
      symbol: 'hwHLP',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/hwHLP.svg',
    },
    {
      chainId: 999,
      address: '0xfd739d4e423301ce9385c1fb8850539d657c296d',
      decimals: 18,
      name: 'Kinetiq Staked HYPE',
      symbol: 'kHYPE',
      tags: ['Top'],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/kHYPE.svg',
    },
    {
      chainId: 999,
      address: '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34',
      decimals: 18,
      name: 'USDe',
      symbol: 'USDe',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/usde.svg',
    },
    {
      chainId: 999,
      address: '0x3FA145caD2C8108A68cfc803A8e1aE246C36dF3e',
      decimals: 18,
      name: 'HyperStrategy',
      symbol: 'HSTR',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/hstr.svg',
    },
    {
      chainId: 999,
      address: '0x99750393c5B40093A53ccD2d8e9f61EF4F401826',
      decimals: 18,
      name: 'BULBUL',
      symbol: 'BULBUL',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/bulbul.svg',
    },
    {
      chainId: 999,
      address: '0xf2E6a23B1aA09565FDb3a77AF7772709De3f4F95',
      decimals: 6,
      name: 'LILLY',
      symbol: 'LILLY',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/lilly.svg',
    },
    {
      chainId: 999,
      address: '0xca79db4B49f608eF54a5CB813FbEd3a6387bC645',
      decimals: 18,
      name: 'USDXL',
      symbol: 'USDXL',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/usdxl.svg',
    },
    {
      chainId: 999,
      address: '0x1359b05241cA5076c9F59605214f4F84114c0dE8',
      decimals: 6,
      name: 'WHLP',
      symbol: 'WHLP',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/whlp.svg',
    },
    {
      chainId: 999,
      address: '0xf4D9235269a96aaDaFc9aDAe454a0618eBE37949',
      decimals: 6,
      name: 'XAUt0',
      symbol: 'XAUt0',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/xaut0.svg',
    },
    {
      chainId: 999,
      address: '0x11735dBd0B97CfA7Accf47d005673BA185f7fd49',
      decimals: 18,
      name: 'CATBAL',
      symbol: 'CATBAL',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/catbal.svg',
    },
    {
      chainId: 999,
      address: '0x1bEe6762F0B522c606DC2Ffb106C0BB391b2E309',
      decimals: 18,
      name: 'PiP',
      symbol: 'PiP',
      tags: [],
      logoURI: 'https://raw.githubusercontent.com/HyperBrickLabs/hyperbrick-tokenlists/refs/heads/main/logos/pip.svg',
    },
  ],
};
